# .goreleaser.yaml
version: 2

before:
  hooks:
    - make prepare

builds:
  - main: ./main.go
    binary: tdx2db
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

release:
  github:
    owner: nickeyfff
    name: tdx2db

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

dockers_v2:
  - id: ghcr
    dockerfile: ./Containerfile
    platforms:
      - linux/amd64
    images:
      - "ghcr.io/nickeyfff/tdx2db"
    tags:
      - "{{ .Version }}"
      - "latest"
    labels:
      "org.opencontainers.image.title": "tdx2db"
      "org.opencontainers.image.description": "Convert and import TDX data into DuckDB"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
